spring.application.name=urlshortener
spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortener
spring.datasource.username=urlshortener
spring.datasource.password=urlshortener
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=epnECO7lo5c9nroK1RrznoMqex2wzNF61fXOh7cCPYJ1oXN88EXhTDpfU9LhLZQ71KAGLGOpT4EoI6mJWDQYyH
jwt.expiration=86400000
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis